version: "3.7"

services:
  db:
    container_name: symfony_db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
  
  app:
    container_name: symfony_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment: 
      APP_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@db/symfony
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - .docker/nginx.conf:/etc/nginx/nginx.conf
      - .docker/symfony.dev.ini:/etc/php7/conf.d/symfony.ini
      - .docker/symfony.dev.ini:/etc/php7/cli/conf.d/symfony.ini
      - .docker/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - .docker/php-fpm.conf:/etc/php7/php-fpm.d/php-fpm.conf
      - .docker/supervisord.conf:/etc/supervisord.conf
      - .:/symfony:cached
    depends_on: 
      - db